version: '2.1'

services:
    log-scanner:
        container_name: log-scanner
        build: ./
        ports:
            - 5000:5000
        environment:
            - LOG_SCANNER_SECRET_KEY=verysecret
            - LOG_SCANNER_DB_URI=postgres://postgres:postgres@db:5432/logscanner
        depends_on:
            db:
                condition: service_healthy

    db:
        container_name: log-scanner-db
        build: ./db
        environment:
            POSTGRES_PASSWORD: postgres
        healthcheck:
            test: exit 0
